name: AntiBow
main: uk.co.ElmHoe.Bukkit.AntiBow
version: 1.2.3
author: ElmHoe
load: POSTWORLD
depend: [WorldGuard, WorldEdit]
commands:
   antibow:
      description: This allows a user with permission or op to be able to make a region not have any bow usage.
      aliases: [ab]
      usage: /<command> [args]